name = "powerwindow-api"
main = "worker/src/index.js"
compatibility_date = "2026-07-06"
workers_dev = true
preview_urls = false
routes = [
  { pattern = "api.powerwindow.energy", custom_domain = true }
]

[[kv_namespaces]]
binding = "MARKET_CACHE"
id = "01aae04ae16d486da0ae2c56322bc426"
